#!/bin/bash

echo "now creating .ogg"
gst-launch-1.0 multifilesrc location="x.%02d.png" index=0 caps="image/png,framerate=\(fraction\)20/1" ! pngdec ! videorate ! videoconvert ! videorate ! theoraenc ! oggmux ! filesink location="x.ogg"

echo "now creating .anim.gif"
# doc:   http://blog.pkh.me/p/21-high-quality-gif-with-ffmpeg.html
# needs: ffmpeg

palette="/tmp/palette.png"

#filters="fps=15,scale=320:-1:flags=lanczos"
filters="fps=20,scale=640:-1:flags=lanczos"

ffmpeg -v warning -i x.ogg -vf "$filters,palettegen" -y $palette
ffmpeg -v warning -i x.ogg -i $palette -lavfi "$filters [x]; [x][1:v] paletteuse" -y $1.anim.gif
