#!/bin/bash
T=13 # trigger GPIO (Broadcom numbering), GPIO13 has hardware PWM
S=9  # trigger length in microseconds
if [ "$2" != "" ]; then T=$2; fi
if [ "$1" != "" ]; then S=$1; fi

if [ ! -f /var/run/pigpio.pid ]; then sudo pigpiod; sleep 0.5; fi

N=/dev/null

pigs wvclr                                   # clear all wavefoms
pigs m $T w                                  # set GPIO into OUTPUT mode
pigs wvag $((1<<T)) 0 $S 0 $((1<<T)) 0  >$N  # add pulse to waveform
pigs wvcre   >$N                             # create wave from pulses (1st 0)
pigs wvtx 0  >$N                             # transmit wave 0
